language: node_js
node_js:
  - '4'

sudo: required

services:
  - docker

before_script:
  - sleep 5

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/reproducibleresearch
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $REPO:$TAG:$COMMIT
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
